# https://taskfile.dev
version: "3"

vars:
  BINARY: operator
  CMD_DIR: ./cmd/operator
  PORT: '{{.PORT | default "8084"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  build:
    desc: Build the operator service binary
    cmds:
      - go build -o bin/{{.BINARY}} {{.CMD_DIR}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - bin/{{.BINARY}}

  test:
    desc: Run all tests with race detector
    cmds:
      - go test -race -count=1 -cover ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  run:
    desc: Run the operator service locally
    cmds:
      - go run {{.CMD_DIR}}
    env:
      PORT: "{{.PORT}}"
      LOG_LEVEL: debug

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
