#!/usr/bin/env bash
# dump-ci-report.sh — Generates ci-report/REPORT.md: a single file that an LLM
# can read to understand the current state of the Turbo Engine platform.
#
# Sections:
#   1. Service health status
#   2. Smoke test results (from smoke-results.json)
#   3. Trace summary (from traces.json)
#   4. Screenshot paths
#   5. Docker compose logs (last 200 lines per service)
#   6. Errors and warnings from logs
#
# Usage:
#   ./hack/scripts/dump-ci-report.sh
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPORT_DIR="${ROOT_DIR}/ci-report"
REPORT_FILE="${REPORT_DIR}/REPORT.md"
COMPOSE_FILE="${ROOT_DIR}/infra/docker/docker-compose.yml"

SMOKE_RESULTS="${REPORT_DIR}/smoke-results.json"
TRACES_FILE="${REPORT_DIR}/traces.json"
SCREENSHOT_DIR="${REPORT_DIR}/screenshots"

GATEWAY_PORT="${GATEWAY_PORT:-8080}"
REGISTRY_PORT="${REGISTRY_PORT:-8081}"
BUILDER_PORT="${BUILDER_PORT:-8082}"
ENVMANAGER_PORT="${ENVMANAGER_PORT:-8083}"
OPERATOR_PORT="${OPERATOR_PORT:-8084}"
CONSOLE_PORT="${CONSOLE_PORT:-3000}"

LOG_TAIL_LINES=200

mkdir -p "${REPORT_DIR}"

# ---------------------------------------------------------------------------
# Color helpers (for terminal output, not the report)
# ---------------------------------------------------------------------------
CYAN='\033[0;36m'
GREEN='\033[0;32m'
RESET='\033[0m'

info()  { printf "${CYAN}[INFO]${RESET}  %s\n" "$*"; }
ok()    { printf "${GREEN}[OK]${RESET}    %s\n" "$*"; }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
check_health() {
  local name="$1"
  local url="$2"
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' "$url" 2>/dev/null || echo "000")
  if [[ "$code" == "200" ]]; then
    echo "HEALTHY (HTTP 200)"
  else
    echo "UNHEALTHY (HTTP ${code})"
  fi
}

# ---------------------------------------------------------------------------
# Build the report
# ---------------------------------------------------------------------------
info "Generating CI report: ${REPORT_FILE}"

exec 3>&1           # Save stdout
exec > "${REPORT_FILE}"  # Redirect stdout to report file

cat <<'HEADER'
# Turbo Engine — CI Report

> Auto-generated by `hack/scripts/dump-ci-report.sh`.
> This file is designed to be consumed by Claude Code to understand the
> current state of the platform.

HEADER

printf "**Generated at:** %s\n\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- Section 1: Service Health -----------------------------------------------
cat <<'EOF'
---

## 1. Service Health Status

EOF

printf "| Service | Endpoint | Status |\n"
printf "|---------|----------|--------|\n"

declare -A HEALTH_ENDPOINTS=(
  [gateway]="http://localhost:${GATEWAY_PORT}/healthz"
  [registry]="http://localhost:${REGISTRY_PORT}/healthz"
  [builder]="http://localhost:${BUILDER_PORT}/healthz"
  [envmanager]="http://localhost:${ENVMANAGER_PORT}/healthz"
  [operator]="http://localhost:${OPERATOR_PORT}/healthz"
  [console]="http://localhost:${CONSOLE_PORT}/"
)

for svc in gateway registry builder envmanager operator console; do
  url="${HEALTH_ENDPOINTS[$svc]}"
  status=$(check_health "$svc" "$url")
  printf "| %s | \`%s\` | %s |\n" "$svc" "$url" "$status"
done

echo ""

# --- Section 2: Smoke Test Results -------------------------------------------
cat <<'EOF'
---

## 2. Smoke Test Results

EOF

if [[ -f "$SMOKE_RESULTS" ]]; then
  # Extract summary.
  total=$(grep -o '"total":\s*[0-9]*' "$SMOKE_RESULTS" | grep -o '[0-9]*' || echo "?")
  passed=$(grep -o '"passed":\s*[0-9]*' "$SMOKE_RESULTS" | grep -o '[0-9]*' || echo "?")
  failed=$(grep -o '"failed":\s*[0-9]*' "$SMOKE_RESULTS" | grep -o '[0-9]*' || echo "?")

  if [[ "$failed" == "0" ]]; then
    printf "**Result: ALL %s TESTS PASSED**\n\n" "$total"
  else
    printf "**Result: %s FAILED** (%s passed, %s total)\n\n" "$failed" "$passed" "$total"
  fi

  printf "| Test | Status | Detail | Duration |\n"
  printf "|------|--------|--------|----------|\n"

  # Parse individual test results (basic grep-based extraction).
  # Each test is a JSON object in the tests array.
  while IFS= read -r line; do
    name=$(echo "$line" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)
    status=$(echo "$line" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
    detail=$(echo "$line" | grep -o '"detail":"[^"]*"' | cut -d'"' -f4)
    duration=$(echo "$line" | grep -o '"duration_ms":[0-9]*' | cut -d: -f2)

    if [[ -n "$name" ]]; then
      local_icon="PASS"
      [[ "$status" == "fail" ]] && local_icon="FAIL"
      printf "| %s | %s | %s | %sms |\n" "$name" "$local_icon" "$detail" "${duration:-0}"
    fi
  done < <(grep -o '{[^}]*}' "$SMOKE_RESULTS" | grep '"name"')

  echo ""
  printf "<details>\n<summary>Raw JSON</summary>\n\n\`\`\`json\n"
  cat "$SMOKE_RESULTS"
  printf "\n\`\`\`\n</details>\n\n"
else
  echo "_No smoke test results found. Run \`hack/scripts/run-smoke-tests.sh\` first._"
  echo ""
fi

# --- Section 3: Trace Summary ------------------------------------------------
cat <<'EOF'
---

## 3. Trace Summary

EOF

if [[ -f "$TRACES_FILE" ]]; then
  captured_at=$(grep -o '"captured_at":"[^"]*"' "$TRACES_FILE" | cut -d'"' -f4 || echo "unknown")
  printf "**Captured at:** %s\n\n" "$captured_at"

  for svc in registry builder envmanager operator gateway; do
    # Count traces per service by counting traceID occurrences within the service block.
    count=$(grep -c '"traceID"' "$TRACES_FILE" 2>/dev/null || echo "0")
    printf "- **%s**: see traces.json for details\n" "$svc"
  done

  total_size=$(wc -c < "$TRACES_FILE" 2>/dev/null || echo "0")
  printf "\n_Full trace data: \`ci-report/traces.json\` (%s bytes)_\n\n" "$total_size"
else
  echo "_No trace data found. Run \`hack/scripts/capture-traces.sh\` first._"
  echo ""
fi

# --- Section 4: Screenshot Paths ---------------------------------------------
cat <<'EOF'
---

## 4. Screenshots

EOF

if [[ -d "$SCREENSHOT_DIR" ]] && ls "$SCREENSHOT_DIR"/* &>/dev/null 2>&1; then
  printf "| Page | File | Size |\n"
  printf "|------|------|------|\n"
  for f in "${SCREENSHOT_DIR}"/*; do
    fname=$(basename "$f")
    page="${fname%.*}"
    size=$(wc -c < "$f" 2>/dev/null || echo "0")
    printf "| %s | \`ci-report/screenshots/%s\` | %s bytes |\n" "$page" "$fname" "$size"
  done
  echo ""
else
  echo "_No screenshots found. Run \`hack/scripts/capture-screenshots.sh\` first._"
  echo ""
fi

# --- Section 5: Docker Compose Logs ------------------------------------------
cat <<'EOF'
---

## 5. Service Logs (last 200 lines each)

EOF

SERVICES=(registry builder envmanager operator gateway console otel-collector jaeger prometheus)

for svc in "${SERVICES[@]}"; do
  printf "### %s\n\n" "$svc"
  printf "\`\`\`\n"

  if [[ -f "$COMPOSE_FILE" ]]; then
    docker compose -f "$COMPOSE_FILE" logs --tail="${LOG_TAIL_LINES}" --no-color "$svc" 2>/dev/null || echo "(no logs available — service may not be running)"
  else
    echo "(docker-compose.yml not found)"
  fi

  printf "\`\`\`\n\n"
done

# --- Section 6: Errors and Warnings ------------------------------------------
cat <<'EOF'
---

## 6. Errors and Warnings

EOF

printf "Scanning logs for errors and warnings...\n\n"

if [[ -f "$COMPOSE_FILE" ]]; then
  ERRORS_FOUND=false

  for svc in "${SERVICES[@]}"; do
    local_errors=$(docker compose -f "$COMPOSE_FILE" logs --tail=500 --no-color "$svc" 2>/dev/null \
      | grep -iE '(error|panic|fatal|warn|critical|exception|fail)' \
      | tail -20 || true)

    if [[ -n "$local_errors" ]]; then
      ERRORS_FOUND=true
      printf "### %s\n\n" "$svc"
      printf "\`\`\`\n%s\n\`\`\`\n\n" "$local_errors"
    fi
  done

  if ! $ERRORS_FOUND; then
    echo "_No errors or warnings found in service logs._"
    echo ""
  fi
else
  echo "_Cannot scan logs — docker-compose.yml not found._"
  echo ""
fi

# --- Footer -------------------------------------------------------------------
cat <<'EOF'
---

_End of CI Report. For detailed trace data, see `ci-report/traces.json`.
For screenshots, see `ci-report/screenshots/`._
EOF

# Restore stdout.
exec >&3

ok "CI report written to: ${REPORT_FILE}"
info "Size: $(wc -c < "${REPORT_FILE}") bytes"
