#!/usr/bin/env bash
# k8s-dump-report.sh — Generates ci-report/REPORT.md from K8s E2E test
# artifacts. Designed to be consumed by both humans and autonomous agents.
#
# Prerequisites: Run k8s-e2e-tests.sh and k8s-collect-debug.sh first.
#
# Output: ci-report/REPORT.md
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPORT_DIR="${ROOT_DIR}/ci-report"
K8S_DIR="${REPORT_DIR}/k8s"
REPORT_FILE="${REPORT_DIR}/REPORT.md"
NAMESPACE="${K8S_NAMESPACE:-turbo-engine-e2e}"

RESULTS_FILE="${REPORT_DIR}/k8s-e2e-results.json"
TIMELINE_FILE="${K8S_DIR}/timeline.txt"
ACTIONS_FILE="${K8S_DIR}/operator-actions.json"
TRACES_FILE="${REPORT_DIR}/traces.json"
SCREENSHOT_DIR="${REPORT_DIR}/screenshots"

JAEGER_PORT="${JAEGER_PORT:-16686}"
LOG_TAIL_LINES=200

mkdir -p "${REPORT_DIR}" "${K8S_DIR}"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RESET='\033[0m'

info()  { printf "${CYAN}[INFO]${RESET}  %s\n" "$*" >&2; }
ok()    { printf "${GREEN}[OK]${RESET}    %s\n" "$*" >&2; }

# ---------------------------------------------------------------------------
# Capture traces from Jaeger (if port-forwarded)
# ---------------------------------------------------------------------------
info "Attempting to capture traces from Jaeger..."

JAEGER_URL="http://localhost:${JAEGER_PORT}"
jaeger_status=$(curl -s -o /dev/null -w '%{http_code}' "${JAEGER_URL}/" 2>/dev/null || echo "000")

if [[ "$jaeger_status" == "200" ]]; then
  NOW_US=$(( $(date +%s) * 1000000 ))
  START_US=$(( NOW_US - (10 * 60 * 1000000) ))  # last 10 minutes

  {
    printf '{\n'
    printf '  "captured_at": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '  "services": {\n'

    first=true
    for svc in registry builder envmanager operator gateway; do
      if ! $first; then printf ',\n'; fi
      first=false

      trace_data=$(curl -s "${JAEGER_URL}/api/traces?service=${svc}&start=${START_US}&end=${NOW_US}&limit=50&lookback=custom" 2>/dev/null || echo '{"data":[]}')
      printf '    "%s": %s' "$svc" "$trace_data"
    done

    printf '\n  }\n'
    printf '}\n'
  } > "${TRACES_FILE}"

  ok "Traces captured to traces.json"
else
  info "Jaeger not reachable (HTTP ${jaeger_status}) — skipping trace capture"
fi

# ---------------------------------------------------------------------------
# Build the report
# ---------------------------------------------------------------------------
info "Generating report: ${REPORT_FILE}"

exec 3>&1
exec > "${REPORT_FILE}"

cat <<'HEADER'
# Turbo Engine — K8s E2E Report

> Auto-generated by `hack/scripts/k8s-dump-report.sh`.
> Designed for consumption by Claude Code and human reviewers.

HEADER

printf "**Generated at:** %s\n\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- Section 1: Timeline ---------------------------------------------------
cat <<'EOF'
---

## 1. Timeline

EOF

if [[ -f "$TIMELINE_FILE" ]]; then
  printf '```\n'
  cat "$TIMELINE_FILE"
  printf '```\n\n'
else
  echo "_No timeline data._"
  echo ""
fi

# --- Section 2: Test Results ------------------------------------------------
cat <<'EOF'
---

## 2. Test Results

EOF

if [[ -f "$RESULTS_FILE" ]]; then
  total=$(grep -o '"total":\s*[0-9]*' "$RESULTS_FILE" | grep -o '[0-9]*' || echo "?")
  passed=$(grep -o '"passed":\s*[0-9]*' "$RESULTS_FILE" | grep -o '[0-9]*' || echo "?")
  failed=$(grep -o '"failed":\s*[0-9]*' "$RESULTS_FILE" | grep -o '[0-9]*' || echo "?")

  if [[ "$failed" == "0" ]]; then
    printf "**Result: ALL %s TESTS PASSED**\n\n" "$total"
  else
    printf "**Result: %s FAILED** (%s passed, %s total)\n\n" "$failed" "$passed" "$total"
  fi

  printf "| Test | Status | Detail | Duration |\n"
  printf "|------|--------|--------|----------|\n"

  while IFS= read -r line; do
    name=$(echo "$line" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)
    status=$(echo "$line" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
    detail=$(echo "$line" | grep -o '"detail":"[^"]*"' | cut -d'"' -f4)
    duration=$(echo "$line" | grep -o '"duration_ms":[0-9]*' | cut -d: -f2)

    if [[ -n "$name" ]]; then
      icon="PASS"
      [[ "$status" == "fail" ]] && icon="FAIL"
      printf "| %s | %s | %s | %sms |\n" "$name" "$icon" "$detail" "${duration:-0}"
    fi
  done < <(grep -o '{[^}]*}' "$RESULTS_FILE" | grep '"name"')
  echo ""
else
  echo "_No test results found._"
  echo ""
fi

# --- Section 3: Pod Status --------------------------------------------------
cat <<'EOF'
---

## 3. Pod Status

EOF

if [[ -f "${K8S_DIR}/resources.txt" ]]; then
  printf '```\n'
  cat "${K8S_DIR}/resources.txt"
  printf '```\n\n'
else
  echo "_No resource data._"
  echo ""
fi

# --- Section 4: Operator Actions --------------------------------------------
cat <<'EOF'
---

## 4. Operator Reconciliation Actions

EOF

if [[ -f "$ACTIONS_FILE" ]]; then
  count=$(python3 -c "import json; print(json.load(open('${ACTIONS_FILE}'))['count'])" 2>/dev/null || echo 0)
  printf "**Total actions:** %s\n\n" "$count"

  if (( count > 0 )); then
    printf "| Time | Action | Kind | Resource | Details |\n"
    printf "|------|--------|------|----------|----------|\n"

    python3 -c "
import json
data = json.load(open('${ACTIONS_FILE}'))
for a in data['actions'][:30]:
    t = a.get('time','')[-8:] if a.get('time') else ''
    print(f'| {t} | {a.get(\"action\",\"\")} | {a.get(\"resource_kind\",\"\")} | {a.get(\"resource_name\",\"\")} | {a.get(\"details\",\"\")} |')
" 2>/dev/null || echo "_(failed to parse actions)_"
    echo ""
  fi
else
  echo "_No operator actions captured._"
  echo ""
fi

# --- Section 5: Trace Summary ----------------------------------------------
cat <<'EOF'
---

## 5. Trace Summary

EOF

if [[ -f "$TRACES_FILE" ]]; then
  captured_at=$(grep -o '"captured_at":"[^"]*"' "$TRACES_FILE" | cut -d'"' -f4 || echo "unknown")
  printf "**Captured at:** %s\n\n" "$captured_at"

  for svc in registry builder envmanager operator gateway; do
    count=$(python3 -c "
import json
data = json.load(open('${TRACES_FILE}'))
svc_data = data.get('services',{}).get('${svc}',{})
traces = svc_data.get('data',[])
print(len(traces))
" 2>/dev/null || echo "0")
    printf "- **%s**: %s traces\n" "$svc" "$count"
  done

  total_size=$(wc -c < "$TRACES_FILE" 2>/dev/null || echo "0")
  printf "\n_Full trace data: \`ci-report/traces.json\` (%s bytes)_\n\n" "$total_size"
else
  echo "_No trace data. Jaeger may not have been reachable._"
  echo ""
fi

# --- Section 6: Screenshots -------------------------------------------------
cat <<'EOF'
---

## 6. Screenshots

EOF

if [[ -d "$SCREENSHOT_DIR" ]] && ls "$SCREENSHOT_DIR"/* &>/dev/null 2>&1; then
  printf "| Page | File | Size |\n"
  printf "|------|------|------|\n"
  for f in "${SCREENSHOT_DIR}"/*; do
    fname=$(basename "$f")
    page="${fname%.*}"
    size=$(wc -c < "$f" 2>/dev/null || echo "0")
    printf "| %s | \`ci-report/screenshots/%s\` | %s bytes |\n" "$page" "$fname" "$size"
  done
  echo ""
else
  echo "_No screenshots captured._"
  echo ""
fi

# --- Section 7: Service Logs -----------------------------------------------
cat <<'EOF'
---

## 7. Service Logs (last 200 lines each)

EOF

SERVICES=(registry builder envmanager turbo-engine-operator gateway console)

for svc in "${SERVICES[@]}"; do
  LOG_FILE="${K8S_DIR}/logs-${svc}.txt"
  printf "### %s\n\n" "$svc"
  printf '```\n'

  if [[ -f "$LOG_FILE" ]]; then
    tail -n "$LOG_TAIL_LINES" "$LOG_FILE"
  else
    echo "(no logs available)"
  fi

  printf '```\n\n'
done

# --- Section 8: Errors and Warnings ----------------------------------------
cat <<'EOF'
---

## 8. Errors and Warnings

EOF

printf "Scanning logs for errors, panics, and warnings...\n\n"

ERRORS_FOUND=false

for svc in "${SERVICES[@]}"; do
  LOG_FILE="${K8S_DIR}/logs-${svc}.txt"
  if [[ -f "$LOG_FILE" ]]; then
    errors=$(grep -iE '("level":"ERROR"|"level":"error"|panic|fatal|"level":"WARN"|"level":"warn")' "$LOG_FILE" \
      | grep -v 'failed to initialise OTLP' \
      | tail -20 || true)

    if [[ -n "$errors" ]]; then
      ERRORS_FOUND=true
      printf "### %s\n\n" "$svc"
      printf '```\n%s\n```\n\n' "$errors"
    fi
  fi
done

if ! $ERRORS_FOUND; then
  echo "_No errors or warnings found in service logs._"
  echo ""
fi

# --- Section 9: K8s Events -------------------------------------------------
cat <<'EOF'
---

## 9. Kubernetes Events

EOF

if [[ -f "${K8S_DIR}/events.txt" ]]; then
  printf '```\n'
  cat "${K8S_DIR}/events.txt"
  printf '```\n\n'
else
  echo "_No events captured._"
  echo ""
fi

# --- Footer -----------------------------------------------------------------
cat <<'EOF'
---

_End of K8s E2E Report. For full data see `ci-report/` directory._
EOF

exec >&3

ok "Report written to: ${REPORT_FILE}"
info "Size: $(wc -c < "${REPORT_FILE}") bytes"
