#!/usr/bin/env bash
# k8s-dump-report.sh — Generates ci-report/REPORT.md from K8s E2E test
# artifacts. Designed to be consumed by both humans and autonomous agents.
#
# Prerequisites: Run k8s-e2e-tests.sh and k8s-collect-debug.sh first.
#
# Output: ci-report/REPORT.md
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPORT_DIR="${ROOT_DIR}/ci-report"
K8S_DIR="${REPORT_DIR}/k8s"
REPORT_FILE="${REPORT_DIR}/REPORT.md"
NAMESPACE="${K8S_NAMESPACE:-turbo-engine-e2e}"

RESULTS_FILE="${REPORT_DIR}/k8s-e2e-results.json"
TIMELINE_FILE="${K8S_DIR}/timeline.txt"
ACTIONS_FILE="${K8S_DIR}/operator-actions.json"
TRACES_FILE="${REPORT_DIR}/traces.json"
SCREENSHOT_DIR="${REPORT_DIR}/screenshots"

JAEGER_PORT="${JAEGER_PORT:-16686}"
LOG_TAIL_LINES=200

mkdir -p "${REPORT_DIR}" "${K8S_DIR}"

CYAN='\033[0;36m'
GREEN='\033[0;32m'
RESET='\033[0m'

info()  { printf "${CYAN}[INFO]${RESET}  %s\n" "$*" >&2; }
ok()    { printf "${GREEN}[OK]${RESET}    %s\n" "$*" >&2; }

# ---------------------------------------------------------------------------
# Capture traces from Jaeger (if port-forwarded)
# ---------------------------------------------------------------------------
info "Attempting to capture traces from Jaeger..."

JAEGER_URL="http://localhost:${JAEGER_PORT}"
jaeger_status=$(curl -s -o /dev/null -w '%{http_code}' "${JAEGER_URL}/" 2>/dev/null || echo "000")

if [[ "$jaeger_status" == "200" ]]; then
  NOW_US=$(( $(date +%s) * 1000000 ))
  START_US=$(( NOW_US - (10 * 60 * 1000000) ))  # last 10 minutes

  {
    printf '{\n'
    printf '  "captured_at": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '  "services": {\n'

    first=true
    for svc in registry builder envmanager operator gateway orchestrator petstore-mock; do
      if ! $first; then printf ',\n'; fi
      first=false

      trace_data=$(curl -s "${JAEGER_URL}/api/traces?service=${svc}&start=${START_US}&end=${NOW_US}&limit=50&lookback=custom" 2>/dev/null || echo '{"data":[]}')
      printf '    "%s": %s' "$svc" "$trace_data"
    done

    printf '\n  }\n'
    printf '}\n'
  } > "${TRACES_FILE}"

  ok "Traces captured to traces.json"
else
  info "Jaeger not reachable (HTTP ${jaeger_status}) — skipping trace capture"
fi

# ---------------------------------------------------------------------------
# Generate trace viewer (HTML + text summary) before the report so the
# report can inline the textual summary.
# ---------------------------------------------------------------------------
TRACE_VIEWER="${SCRIPT_DIR}/generate-trace-viewer.sh"
if [[ -f "$TRACE_VIEWER" && -f "$TRACES_FILE" ]]; then
  info "Generating trace viewer..."
  bash "$TRACE_VIEWER" || warn "Trace viewer generation failed (non-fatal)"
fi

# ---------------------------------------------------------------------------
# Build the report
# ---------------------------------------------------------------------------
info "Generating report: ${REPORT_FILE}"

exec 3>&1
exec > "${REPORT_FILE}"

cat <<'HEADER'
# Turbo Engine — K8s E2E Report

> Auto-generated by `hack/scripts/k8s-dump-report.sh`.
> Designed for consumption by Claude Code and human reviewers.

HEADER

printf "**Generated at:** %s\n\n" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- Section 1: Timeline ---------------------------------------------------
cat <<'EOF'
---

## 1. Timeline

EOF

if [[ -f "$TIMELINE_FILE" ]]; then
  printf '```\n'
  cat "$TIMELINE_FILE"
  printf '```\n\n'
else
  echo "_No timeline data._"
  echo ""
fi

# --- Section 2: Test Results ------------------------------------------------
cat <<'EOF'
---

## 2. Test Results

EOF

if [[ -f "$RESULTS_FILE" ]]; then
  total=$(grep -o '"total":\s*[0-9]*' "$RESULTS_FILE" | grep -o '[0-9]*' || echo "?")
  passed=$(grep -o '"passed":\s*[0-9]*' "$RESULTS_FILE" | grep -o '[0-9]*' || echo "?")
  failed=$(grep -o '"failed":\s*[0-9]*' "$RESULTS_FILE" | grep -o '[0-9]*' || echo "?")

  if [[ "$failed" == "0" ]]; then
    printf "**Result: ALL %s TESTS PASSED**\n\n" "$total"
  else
    printf "**Result: %s FAILED** (%s passed, %s total)\n\n" "$failed" "$passed" "$total"
  fi

  printf "| Test | Status | Detail | Duration |\n"
  printf "|------|--------|--------|----------|\n"

  while IFS= read -r line; do
    name=$(echo "$line" | grep -o '"name":"[^"]*"' | cut -d'"' -f4)
    status=$(echo "$line" | grep -o '"status":"[^"]*"' | cut -d'"' -f4)
    detail=$(echo "$line" | grep -o '"detail":"[^"]*"' | cut -d'"' -f4)
    duration=$(echo "$line" | grep -o '"duration_ms":[0-9]*' | cut -d: -f2)

    if [[ -n "$name" ]]; then
      icon="PASS"
      [[ "$status" == "fail" ]] && icon="FAIL"
      printf "| %s | %s | %s | %sms |\n" "$name" "$icon" "$detail" "${duration:-0}"
    fi
  done < <(grep -o '{[^}]*}' "$RESULTS_FILE" | grep '"name"')
  echo ""
else
  echo "_No test results found._"
  echo ""
fi

# --- Section 3: Pod Status --------------------------------------------------
cat <<'EOF'
---

## 3. Pod Status

EOF

if [[ -f "${K8S_DIR}/resources.txt" ]]; then
  printf '```\n'
  cat "${K8S_DIR}/resources.txt"
  printf '```\n\n'
else
  echo "_No resource data._"
  echo ""
fi

# --- Section 4: Operator Actions --------------------------------------------
cat <<'EOF'
---

## 4. Operator Reconciliation Actions

EOF

if [[ -f "$ACTIONS_FILE" ]]; then
  count=$(python3 -c "import json; print(json.load(open('${ACTIONS_FILE}'))['count'])" 2>/dev/null || echo 0)
  printf "**Total actions:** %s\n\n" "$count"

  if (( count > 0 )); then
    printf "| Time | Action | Kind | Resource | Details |\n"
    printf "|------|--------|------|----------|----------|\n"

    python3 -c "
import json, re
data = json.load(open('${ACTIONS_FILE}'))
for a in data['actions'][:30]:
    # Parse ISO 8601 timestamp to HH:MM:SS.mmm
    raw = a.get('time', '')
    m = re.search(r'T(\d{2}:\d{2}:\d{2})', raw)
    t = m.group(1) if m else raw[:19]
    action = a.get('action', '')
    kind = a.get('resource_kind', '')
    name = a.get('resource_name', '')
    details = a.get('details', '') or a.get('phase', '')
    print(f'| {t} | {action} | {kind} | {name} | {details} |')
" 2>/dev/null || echo "_(failed to parse actions)_"
    echo ""
  fi
else
  echo "_No operator actions captured._"
  echo ""
fi

# --- Section 5: Trace Summary ----------------------------------------------
cat <<'EOF'
---

## 5. Trace Summary

EOF

if [[ -f "$TRACES_FILE" ]]; then
  captured_at=$(grep -o '"captured_at":"[^"]*"' "$TRACES_FILE" | cut -d'"' -f4 || echo "unknown")
  printf "**Captured at:** %s\n\n" "$captured_at"

  for svc in registry builder envmanager operator gateway; do
    count=$(python3 -c "
import json
data = json.load(open('${TRACES_FILE}'))
svc_data = data.get('services',{}).get('${svc}',{})
traces = svc_data.get('data',[])
print(len(traces))
" 2>/dev/null || echo "0")
    printf "- **%s**: %s traces\n" "$svc" "$count"
  done

  total_size=$(wc -c < "$TRACES_FILE" 2>/dev/null || echo "0")
  printf "\n[**Open trace viewer →**](./traces.html)\n\n"

  # Inline the textual trace summary if available (for Claude to read).
  if [[ -f "${REPORT_DIR}/traces.txt" ]]; then
    printf "<details><summary>Textual trace summary (for automated analysis)</summary>\n\n"
    printf '```\n'
    cat "${REPORT_DIR}/traces.txt"
    printf '```\n\n'
    printf "</details>\n\n"
  fi

  printf "_Full trace data: \`ci-report/traces.json\` (%s bytes)_\n\n" "$total_size"
else
  echo "_No trace data. Jaeger may not have been reachable._"
  echo ""
fi

# --- Section 6: Screenshots -------------------------------------------------
cat <<'EOF'
---

## 6. Screenshots

EOF

FOUND_SCREENSHOTS=false

# Check for per-scenario subdirectories first.
for scenario_dir in "${SCREENSHOT_DIR}"/*/; do
  [ -d "$scenario_dir" ] || continue
  scenario_name=$(basename "$scenario_dir")
  has_images=false
  for f in "${scenario_dir}"*.png "${scenario_dir}"*.jpg "${scenario_dir}"*.html; do
    [ -f "$f" ] && has_images=true && break
  done
  $has_images || continue
  FOUND_SCREENSHOTS=true

  printf "### %s\n\n" "$scenario_name"
  printf "| Page | File | Size |\n"
  printf "|------|------|------|\n"
  for f in "${scenario_dir}"*.png "${scenario_dir}"*.jpg "${scenario_dir}"*.html; do
    [ -f "$f" ] || continue
    fname=$(basename "$f")
    page="${fname%.*}"
    size=$(wc -c < "$f" 2>/dev/null || echo "0")
    printf "| %s | \`ci-report/screenshots/%s/%s\` | %s bytes |\n" "$page" "$scenario_name" "$fname" "$size"
  done
  echo ""

  # Show browser console logs if captured (skip empty files).
  for logf in "${scenario_dir}"*.log; do
    [ -f "$logf" ] || continue
    if ! grep -q '[^[:space:]]' "$logf" 2>/dev/null; then continue; fi
    logname=$(basename "$logf")
    page="${logname%.log}"
    linecount=$(wc -l < "$logf" 2>/dev/null || echo "0")
    echo "<details><summary>Browser console: ${scenario_name}/${page} (${linecount} lines)</summary>"
    echo ""
    echo '```'
    cat "$logf"
    echo '```'
    echo "</details>"
    echo ""
  done
done

# Also check for top-level screenshots (backwards compat).
for f in "${SCREENSHOT_DIR}"/*.png "${SCREENSHOT_DIR}"/*.jpg "${SCREENSHOT_DIR}"/*.html; do
  [ -f "$f" ] || continue
  if ! $FOUND_SCREENSHOTS; then
    FOUND_SCREENSHOTS=true
    printf "| Page | File | Size |\n"
    printf "|------|------|------|\n"
  fi
  fname=$(basename "$f")
  page="${fname%.*}"
  size=$(wc -c < "$f" 2>/dev/null || echo "0")
  printf "| %s | \`ci-report/screenshots/%s\` | %s bytes |\n" "$page" "$fname" "$size"
done
if $FOUND_SCREENSHOTS; then echo ""; fi

if ! $FOUND_SCREENSHOTS; then
  echo "_No screenshots captured._"
  echo ""
fi

# --- Section 7: Service Logs -----------------------------------------------
cat <<'EOF'
---

## 7. Service Logs (last 200 lines each)

EOF

SERVICES=(registry builder envmanager turbo-engine-operator gateway console)

for svc in "${SERVICES[@]}"; do
  LOG_FILE="${K8S_DIR}/logs-${svc}.txt"
  printf "### %s\n\n" "$svc"
  printf '```\n'

  if [[ -f "$LOG_FILE" ]]; then
    tail -n "$LOG_TAIL_LINES" "$LOG_FILE"
  else
    echo "(no logs available)"
  fi

  printf '```\n\n'
done

# Include operator-deployed component logs (captured by k8s-e2e-tests.sh).
COMPONENT_LOGS=()
for f in "${K8S_DIR}"/*-logs.txt; do
  [[ -f "$f" ]] || continue
  fname=$(basename "$f")
  # Skip control-plane logs already rendered above.
  is_cp=false
  for svc in "${SERVICES[@]}"; do
    [[ "$fname" == "logs-${svc}.txt" ]] && is_cp=true
  done
  $is_cp && continue
  COMPONENT_LOGS+=("$f")
done

if [[ ${#COMPONENT_LOGS[@]} -gt 0 ]]; then
  printf "### Operator-deployed components\n\n"
  for f in "${COMPONENT_LOGS[@]}"; do
    comp=$(basename "$f" .txt | sed 's/-logs$//')
    printf "#### %s\n\n" "$comp"
    printf '```\n'
    tail -n "$LOG_TAIL_LINES" "$f"
    printf '```\n\n'
  done
fi

# --- Section 8: Errors and Warnings ----------------------------------------
cat <<'EOF'
---

## 8. Errors and Warnings

EOF

printf "Scanning logs for errors, panics, and warnings...\n\n"

ERRORS_FOUND=false

# Scan control-plane logs.
for svc in "${SERVICES[@]}"; do
  LOG_FILE="${K8S_DIR}/logs-${svc}.txt"
  if [[ -f "$LOG_FILE" ]]; then
    errors=$(grep -iE '("level":"ERROR"|"level":"error"|panic|fatal|"level":"WARN"|"level":"warn")' "$LOG_FILE" \
      | grep -v 'failed to initialise OTLP' \
      | tail -20 || true)

    if [[ -n "$errors" ]]; then
      ERRORS_FOUND=true
      printf "### %s\n\n" "$svc"
      printf '```\n%s\n```\n\n' "$errors"
    fi
  fi
done

# Scan operator-deployed component logs.
for f in "${COMPONENT_LOGS[@]:-}"; do
  [[ -z "$f" || ! -f "$f" ]] && continue
  comp=$(basename "$f" .txt | sed 's/-logs$//')
  errors=$(grep -iE '("level":"ERROR"|"level":"error"|panic|fatal|"level":"WARN"|"level":"warn")' "$f" \
    | tail -20 || true)

  if [[ -n "$errors" ]]; then
    ERRORS_FOUND=true
    printf "### %s (component)\n\n" "$comp"
    printf '```\n%s\n```\n\n' "$errors"
  fi
done

if ! $ERRORS_FOUND; then
  echo "_No errors or warnings found in service logs._"
  echo ""
fi

# --- Section 9: K8s Events -------------------------------------------------
cat <<'EOF'
---

## 9. Kubernetes Events

EOF

if [[ -f "${K8S_DIR}/events.txt" ]]; then
  printf '```\n'
  cat "${K8S_DIR}/events.txt"
  printf '```\n\n'
else
  echo "_No events captured._"
  echo ""
fi

# --- Footer -----------------------------------------------------------------
cat <<'EOF'
---

_End of K8s E2E Report. For full data see `ci-report/` directory._
EOF

exec >&3

ok "Report written to: ${REPORT_FILE}"
info "Size: $(wc -c < "${REPORT_FILE}") bytes"
